version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: tpfoyer_mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tpFoyer17
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: hssan577/azerty:1.0.0
    container_name: azerty
    restart: on-failure
    ports:
      - "8082:8082"
    

    tty: true

volumes:
  db:
